[window] 

opacity = 0.7

padding.x = 10
padding.y = 10

decorations = "Buttonless"
decorations_theme_variant ="Light" # "Dark"
startup_mode = "Maximized"
title = "None"


[font]

normal.family = "monospace"
bold.family = "monospace"
italic.family = "monospace"
bold_italic.family = "monospace"

size = 9.0
